[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "astro530"
version = "0.1.0"
dependencies = ["numpy", "matplotlib", "astropy"]

[tool.setuptools.packages.find]
where = ["."]